- name: Generate and Upload SSH Keys to VMs
  hosts: all
  vars:
    local_ssh_key_dir: "../ssh_keys"
    ssh_key_filename: "ansible_ssh_key"

  tasks:
    - name: Ensure local SSH key directory exists
      ansible.builtin.file:
        path: "{{ local_ssh_key_dir }}"
        state: directory
        mode: '0755'
      tags:
        - ssh_generation

    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: "{{ local_ssh_key_dir }}/{{ ssh_key_filename }}"
        size: 2048
      tags:
        - ssh_generation

    - name: Upload public key to VM
      ansible.builtin.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', local_ssh_key_dir + '/' + ssh_key_filename + '.pub') }}"
      tags:
        - ssh_upload